project:
  name: RetailIQ
  random_state: 42

data:
  dataset_name: Online Shoppers Purchasing Intention
  target: Revenue
  test_size: 0.20
  validation_size: 0.20

model:
  type: RandomForestClassifier
  n_estimators: 300
  max_depth: 12
  min_samples_split: 2
  min_samples_leaf: 5
  class_weight: balanced
  n_jobs: -1
  random_state: 42

mlflow:
  experiment_name: RetailIQ_Purchase_Prediction
  tracking_uri: sqlite:///retailiq_mlflow.db
